---
abstract: ~
author:
  - 'Toby Corkindale, L<mailto:tjc@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::Exception: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.08'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Retry
no_index:
  directory:
    - inc
    - t
requires:
  Moo: 0
  perl: 5.8.1
resources:
  license: http://opensource.org/licenses/artistic-license-2.0.php
  repository: http://github.com/TJC/Retry
version: '1.00'
